In [3]:
import numpy as np
from pprint import pprint
from sympy import *

In [4]:
def lu(A):
    """
    Implementación del método LU
    Entradas:
    A -- matriz cuadrada

    Salidas:
    L, U -- matrices de la descomposición
    None -- en caso de no ser posible la descomposición
    """
    n = len(A)
    # crear matrices nulas
    L = [[0 for x in range(n)] for x in range(n)]
    U = [[0 for x in range(n)] for x in range(n)]

    # Doolittle
    L[0][0] = 1
    U[0][0] = A[0][0]

    if abs(L[0][0]*U[0][0]) <= 1e-15:
        print("Imposible descomponer")
        return None

    for j in range(1, n):
        U[0][j] = A[0][j]/L[0][0]
        L[j][0] = A[j][0]/U[0][0]

    for i in range(1, n-1):
        L[i][i] = 1
        s = sum([L[i][k]*U[k][i] for k in range(i)])
        U[i][i] = A[i][i] - s

        if abs(L[i][i]*U[i][i]) <= 1e-15:
            print("Imposible descomponer")
            return None

        for j in range(i+1, n):
            s1 = sum([L[i][k]*U[k][j] for k in range(i)])
            s2 = sum([L[j][k]*U[k][i] for k in range(i)])
            U[i][j] = A[i][j] - s1
            L[j][i] = (A[j][i] - s2)/U[i][i]

    L[n-1][n-1] = 1.0
    s3 = sum([L[n-1][k]*U[k][n-1] for k in range(n)])
    U[n-1][n-1] = A[n-1][n-1] - s3

    if abs(L[n-1][n-1]*U[n-1][n-1]) <= 1e-15:
        print("Imposible descomponer")
        return None

    print("Matriz L:\n")
    pprint(Matrix(L))
    print("Matriz U:\n")
    pprint(Matrix(U))
    return L, U

In [13]:
def distinf(x, y):
    """Implementación distancia dada por la norma infinito"""
    return max([abs(x[i] - y[i]) for i in range(len(x))])


def Jacobi(A, b, x0, TOL, MAX):
    """
    Implementación del método de Jacobi
    Entradas:
    A -- matriz cuadrada
    b -- vector
    x0 -- aproximación inicial
    TOL -- tolerancia
    MAX -- número máximo de iteraciones

    Salida:
    x -- aproximación a solución del sistema Ax = b
    None -- en caso de agotar las iteraciones o presentar errores
    """
    n = len(A)
    x = [0.0 for x in range(n)]
    k = 1
    while k <= MAX:
        for i in range(n):
            if abs(A[i][i]) <= 1e-15:
                print("Imposible iterar")
                return None
            s = sum([A[i][j]*x0[j] for j in range(n) if j != i])
            x[i] = (b[i] - s)/A[i][i]
        pprint(x)
        if distinf(x, x0) < TOL:
            print(r"Solución encontrada")
            return x
        k += 1
        for i in range(n):
            x0[i] = x[i]
    print("Iteraciones agotadas")
    return None

def GaussSeidel(A, b, x0, TOL, MAX):
    """
    Implementación del método de Gauss-Seidel
    Entradas:
    A -- matriz cuadrada
    b -- vector
    x0 -- aproximación inicial
    TOL -- tolerancia
    MAX -- número máximo de iteraciones

    Salida:
    x -- aproximación a solución del sistema Ax = b
    None -- en caso de agotar las iteraciones o presentar errores
    """
    n = len(A)
    x = [0.0 for x in range(n)]
    k = 1
    while k <= MAX:
        for i in range(n):
            if abs(A[i][i]) <= 1e-15:
                print("Imposible iterar")
                return None
            s1 = sum([A[i][j]*x[j] for j in range(i)])
            s2 = sum([A[i][j]*x0[j] for j in range(i+1, n)])
            x[i] = (b[i] - s1 - s2)/A[i][i]
        pprint(x)
        if distinf(x, x0) < TOL:
            print(r"Solución encontrada")
            return x
        k += 1
        for i in range(n):
            x0[i] = x[i]
    print("Iteraciones agotadas")
    return None

In [23]:
a = np.array([[11, -3, 0],
              [-3, 6, -1],
              [0, -1, 3]])
b = np.array([30, 5, -25])
sol = np.linalg.solve(a, b)
print(sol)

[ 3.  1. -8.]


In [6]:
L, U = lu(a)

Matriz L:

⎡        1                   0            0 ⎤
⎢                                           ⎥
⎢-0.272727272727273          1            0 ⎥
⎢                                           ⎥
⎣        0           -0.192982456140351  1.0⎦
Matriz U:

⎡11        -3.0               0        ⎤
⎢                                      ⎥
⎢0   5.18181818181818        -1.0      ⎥
⎢                                      ⎥
⎣0          0          2.80701754385965⎦


In [16]:
print(-3/11, -11/57, 57/11, 160/57)

-0.2727272727272727 -0.19298245614035087 5.181818181818182 2.807017543859649


In [26]:
L = np.array(L)
z = np.linalg.solve(L, b)
print(z)
U = np.array(U)
x = np.linalg.solve(U, z)
print(x)

[ 30.          13.18181818 -22.45614035]
[ 3.  1. -8.]


In [53]:
print("Matriz A:")
pprint(a)
print("Vector b:")
pprint(b)
print("Semilla x0:")
sem=[2, 0, -7]
x0=sem.copy()
print(x0)
print("Iteración de Jacobi")
Jacobi(a, b, x0, 1e-4, 4)

Matriz A:
[[11 -3  0] 
 [-3  6 -1] 
 [ 0 -1  3]]
Vector b:
[ 30   5 -25]
Semilla x0:
[2, 0, -7]
Iteración de Jacobi
[2.727272727272727, 0.6666666666666666, -8.333333333333334]
[2.909090909090909, 0.808080808080808, -8.11111111111111]
[2.9476584022038566, 0.936026936026936, -8.063973063973064]
[2.982552800734619, 0.9631670237730843, -8.021324354657688]
Iteraciones agotadas
[2, 0, -7]


In [54]:
print("Matriz A:")
pprint(a)
print("Vector b:")
pprint(b)
print("Semilla x0:")
x0=sem.copy()
print(x0)
print('m')
GaussSeidel(a, b, x0, 1e-4, 4)

Matriz A:
[[11 -3  0] 
 [-3  6 -1] 
 [ 0 -1  3]]
Vector b:
[ 30   5 -25]
Semilla x0:
[2, 0, -7]
m
[2.727272727272727, 1.0303030303030303, -7.98989898989899]
[3.0082644628099175, 1.0058157330884605, -7.998061422303846]
[3.001586109024126, 1.0011161507947552, -7.999627949735082]
[3.000304404762206, 1.0002142107585892, -7.999928596413803]
Iteraciones agotadas
